<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $boardName }} - Tasks Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1e3a5f;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #1e3a5f;
            margin: 0;
        }
        .header p {
            color: #666;
            margin: 5px 0 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }
        th {
            background-color: #1e3a5f;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            vertical-align: top !important;
        }
        td {
            border: 1px solid #ddd;
            padding: 8px;
            vertical-align: top !important;
            white-space: normal;
            word-wrap: break-word;
        }
        /* Kolom Title (kolom 2) */
        td:nth-child(2) {
            width: 25%;
        }
        /* Kolom Description (kolom 3) */
        td:nth-child(3) {
            width: 30%;
        }
        tr {
            vertical-align: top !important;
        }
        tr td {
            vertical-align: top !important;
        }
        tbody tr td {
            vertical-align: top !important;
        }
        .priority-high {
            color: #ef4444;
            font-weight: bold;
        }
        .priority-medium {
            color: #f59e0b;
        }
        .priority-low {
            color: #10b981;
        }
        .archived {
            color: #6b7280;
            font-style: italic;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $boardName }}</h1>
        <p>Tasks Report - Generated on {{ $exportDate }}</p>
        <p>Total Tasks: {{ count($tasks) }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>List</th>
                <th>Priority</th>
                <th>Due Date</th>
                <th>Assignees</th>
                <th>Status</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tasks as $task)
            <tr>
                <td>{{ $task->id }}</td>
                <td>{{ $task->title }}</td>
                <td style="white-space: normal; word-wrap: break-word;">{{ $task->description ? nl2br(e($task->description)) : '-' }}</td>
                <td>{{ $task->taskList->name ?? '-' }}</td>
                <td class="priority-{{ $task->priority }}">
                    {{ ucfirst($task->priority) }}
                </td>
                <td>{{ $task->due_date ? $task->due_date->format('d M Y') : '-' }}</td>
                <td>{{ $task->assignees->pluck('name')->implode(', ') ?: '-' }}</td>
                <td class="{{ $task->isArchived() ? 'archived' : '' }}">
                    {{ $task->isArchived() ? 'Archived' : 'Active' }}
                </td>
                <td>{{ $task->created_at ? $task->created_at->format('d M Y') : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        Generated by Kanban Board System • {{ date('Y') }}
    </div>
</body>
</html>